### ISSUE TITLE
Environment issue

### ISSUE THREAD

**Issue by JohnsonQi** [rickstaa/panda_autograsp#156]
## Problem description

I want to simulate. However, I can't successfully run : `roslaunch panda_autograsp panda_autograsp.py` after running the following install commands:

```
catkin build -j4 -DCMAKE_BUILD_TYPE=Release -DFranka_DIR:PATH=/libfranka/build -Dfreenect2_DIR=/opt/freenect2/lib/cmake/freenect2"
cd ~/panda_autograsp_ws/src
pip install .
```

### Your environment
**ROS Distro:** [Indigo|Jade|Kinetic] Kinetic
**OS Version:** e.g. Ubuntu 16.04
**python:** 2.7

### Problem 1

run：`roslaunch panda_autograsp panda_autograsp.py`

```
[Error] [OpenGLDepthPacketProcessorImpl] GLFW error 65543 GLX: Failed to create context: GLXBadFBConfig
[Error] [OpenGLDepthPacketProcessor] Failed to create opengl window.
[FATAL] [1584971719.851185887]: Failed to load nodelet '/kinect2_points_xyzrgb_hdof typedepth_image_proc/point_cloud_xyzrgbto managerkinect2'
[FATAL] [1584971719.851311419]: Failed to load nodelet '/kinect2_depth_image_proc_hdof typedepth_image_proc/convert_metricto managerkinect2'
[FATAL] [1584971719.851379355]: Failed to load nodelet '/kinect2_depth_image_proc_sdof typedepth_image_proc/convert_metricto managerkinect2'
[FATAL] [1584971719.851382338]: Failed to load nodelet '/kinect2_bridgeof typekinect2_bridge/kinect2_bridge_nodeletto managerkinect2'
[FATAL] [1584971719.851392479]: Failed to load nodelet '/kinect2_depth_image_proc_qhdof typedepth_image_proc/convert_metricto managerkinect2'
[FATAL] [1584971719.851464927]: Failed to load nodelet '/kinect2_points_xyzrgb_sdof typedepth_image_proc/point_cloud_xyzrgbto managerkinect2'
[FATAL] [1584971719.851546718]: Failed to load nodelet '/kinect2_points_xyzrgb_qhdof typedepth_image_proc/point_cloud_xyzrgbto managerkinect2'
```

#### Possible cause
I guess it's caused by no real Kinect v2.

### Problem 2
Don't know what happened.

```
[ INFO] [1584971719.892685049]: compiled against OGRE version 1.9.0 (Ghadamon)
Traceback (most recent call last):
File "/home/johnson/panda_autograsp_ws/src/panda_autograsp/nodes/tf2_broadcaster.py", line 21, in
from panda_autograsp import Tf2Broadcaster
File "/home/johnson/panda_autograsp_ws/devel/lib/python2.7/dist-packages/panda_autograsp/init.py", line 35, in
exec(__fh.read())
File "", line 2, in
File "/home/johnson/panda_autograsp_ws/src/panda_autograsp/src/panda_autograsp/loggers.py", line 22, in
import colorlog
ImportError: No module named colorlog
Traceback (most recent call last):
File "/home/johnson/panda_autograsp_ws/src/panda_autograsp/nodes/moveit_planner_server.py", line 44, in
from panda_autograsp import MoveitPlannerServer
File "/home/johnson/panda_autograsp_ws/devel/lib/python2.7/dist-packages/panda_autograsp/init.py", line 35, in
exec(__fh.read())
File "", line 2, in
File "/home/johnson/panda_autograsp_ws/src/panda_autograsp/src/panda_autograsp/loggers.py", line 22, in
import colorlog
ImportError: No module named colorlog
Traceback (most recent call last):
File "/home/johnson/panda_autograsp_ws/src/panda_autograsp/nodes/panda_autograsp_server.py", line 32, in
from panda_autograsp import PandaAutograspServer
File "/home/johnson/panda_autograsp_ws/devel/lib/python2.7/dist-packages/panda_autograsp/init.py", line 35, in
exec(__fh.read())
File "", line 2, in
File "/home/johnson/panda_autograsp_ws/src/panda_autograsp/src/panda_autograsp/loggers.py", line 22, in
import colorlog
ImportError: No module named colorlog
================================================================================REQUIRED process [tf2_broadcaster-16] has died!
process has died [pid 39153, exit code 1, cmd /home/johnson/panda_autograsp_ws/src/panda_autograsp/nodes/tf2_broadcaster.py panda_link0 calib_frame __name:=tf2_broadcaster __log:=/home/johnson/.ros/log/e054c018-6d02-11ea-9c9f-00505621cb8c/tf2_broadcaster-16.log].
log file: /home/johnson/.ros/log/e054c018-6d02-11ea-9c9f-00505621cb8c/tf2_broadcaster-16*.log
Initiating shutdown!
[moveit_planner_server-19] killing on exit
[grasp_planner_server-18] killing on exit
Traceback (most recent call last):
File "/home/johnson/panda_autograsp_ws/src/panda_autograsp/nodes/grasp_planner_server.py", line 31, in
from gqcnn.utils import GripperMode
File "/home/johnson/panda_autograsp_ws/devel/lib/python2.7/dist-packages/gqcnn/init.py", line 35, in
exec(__fh.read())
File "", line 29, in
File "/home/johnson/panda_autograsp_ws/src/gqcnn/gqcnn/model/init.py", line 32, in
[panda_autograsp_server-17] killing on exit
from .tf import GQCNNTF, FCGQCNNTF
File "/home/johnson/panda_autograsp_ws/src/gqcnn/gqcnn/model/tf/init.py", line 29, in
[dyn_reconf_gui-15] killing on exit
from .network_tf import GQCNNTF
File "/home/johnson/panda_autograsp_ws/src/gqcnn/gqcnn/model/tf/network_tf.py", line 44, in
import tensorflow as tf
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/tensorflow/init.py", line 24, in
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/tensorflow/python/init.py", line 52, in
from tensorflow.core.framework.graph_pb2 import *
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in
from google.protobuf import descriptor as _descriptor
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/google/protobuf/init.py", line 37, in
[kinect2_depth_image_proc_sd-14] killing on exit
Traceback (most recent call last):
import('pkg_resources').declare_namespace(name)
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 3251, in
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/shiboken2/files.dir/shibokensupport/signature/loader.py", line 108, in finish_import
def finish_import(module):
KeyboardInterrupt
@_call_aside
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 3235, in _call_aside
f(*args, **kwargs)
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 3287, in _initialize_master_working_set
list(map(working_set.add_entry, sys.path))
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 623, in add_entry
[tf2_broadcaster-16] killing on exit
[kinect2_depth_image_proc_qhd-13] killing on exit
for dist in find_distributions(entry, True):
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 2065, in find_on_path
[kinect2_depth_image_proc_hd-12] killing on exit
for dist in factory(fullpath):
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 2135, in distributions_from_metadata
[rviz_johnson_VM_UBUNTU16_38979_7231073059793820187-5] killing on exit
root, entry, metadata, precedence=DEVELOP_DIST,
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 2592, in from_location
[robot_state_publisher-6] killing on exit
[kinect2_points_xyzrgb_qhd-10] killing on exit
py_version=py_version, platform=platform, **kw
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 2994, in _reload_version
[move_group-4] killing on exit
md_version = self._get_version()
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 2772, in _get_version
version = _version_from_file(lines)
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 2556, in _version_from_file
line = next(iter(version_lines), '')
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 2766, in _get_metadata
if self.has_metadata(name):
File "/home/johnson/envs/ros-grasp2/lib/python2.7/site-packages/pkg_resources/init.py", line 1891, in has_metadata
[joint_state_desired_publisher-3] killing on exit
return name == 'PKG-INFO' and os.path.isfile(self.path)
File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
[kinect2_points_xyzrgb_hd-11] killing on exit
[kinect2_points_xyzrgb_sd-9] killing on exit
[virtual_joint_broadcaster_1-1] killing on exit
[kinect2_bridge-8] killing on exit
[kinect2-7] killing on exit
[joint_state_publisher-2] killing on exit
st = os.stat(path)
PluginManager._discover() force discovery of plugins
RospkgPluginProvider._find_plugins() crawling for plugins of type 'qt_gui'
[rviz_johnson_VM_UBUNTU16_38979_7231073059793820187-5] escalating to SIGTERM
shutting down processing monitor...
... shutting down processing monitor complete
done
```

Could you please tell me what I should do next?

Looking forward to your reply

**Comment by rickstaa** [comment]
@JohnsonQi Thanks a lot for your interest in the package and sorry for the problems you're having. I will try to help you to get the package up and running on your system. Although I quickly test the `panda_autograsp` package with ROS kinetic on ubuntu 16.04, most of the development was done using ROS melodic on ubuntu 18.04. If possible I, therefore, advise you to test out the package on ubuntu 18.04 using ROS melodic. I will create a singularity container later today so we can investigate the problems on your setup. The recipe for this container and the ROS melodic container can be found in the `./containers/singularity` folder. In the meantime, however, let see if we can solve the issues together. 

#### First issue
For the first issue your having I think your right about it being caused by the fact that you don't have a real Kinect camera. As you mentioned in your email the following is stated in the documentation:

![thumbnail_2E02DF0E@FFEA3C30 9A61775E](https://user-images.githubusercontent.com/17570430/77888098-01c5dc00-726c-11ea-95e8-4ef0b4fbeacf.jpg)

What I mean with this statement is that the package is not yet fully working with the simulated Kinect2 camera. This is caused by the fact that the simulated camera from the [common-sensors ](https://github.com/JenniferBuehler/common-sensors) package is publishing camera messages using the topic convention of the [https://wiki.ros.org/openni_launch](https://wiki.ros.org/openni_launch) package. As I experienced some problems when using the [https://wiki.ros.org/openni_launch](https://wiki.ros.org/openni_launch) package with ROS melodic, I during development switched to the [iai_kinect2](https://github.com/code-iai/iai_kinect2) package. As a result, the `panda_autograsp` package expects the camera topics to be published as follows:

```
/kinect2/hd/camera_info
/kinect2/hd/image_color
/kinect2/hd/image_color/compressed
/kinect2/hd/image_color_rect
/kinect2/hd/image_color_rect/compressed
/kinect2/hd/image_depth_rect
/kinect2/hd/image_depth_rect/compressed
/kinect2/hd/image_mono
/kinect2/hd/image_mono/compressed
/kinect2/hd/image_mono_rect
/kinect2/hd/image_mono_rect/compressed
/kinect2/hd/points
/kinect2/qhd/camera_info
/kinect2/qhd/image_color
/kinect2/qhd/image_color/compressed
/kinect2/qhd/image_color_rect
/kinect2/qhd/image_color_rect/compressed
/kinect2/qhd/image_depth_rect
/kinect2/qhd/image_depth_rect/compressed
/kinect2/qhd/image_mono
/kinect2/qhd/image_mono/compressed
/kinect2/qhd/image_mono_rect
/kinect2/qhd/image_mono_rect/compressed
/kinect2/qhd/points
/kinect2/sd/camera_info
/kinect2/sd/image_color_rect
/kinect2/sd/image_color_rect/compressed
/kinect2/sd/image_depth
/kinect2/sd/image_depth/compressed
/kinect2/sd/image_depth_rect
/kinect2/sd/image_depth_rect/compressed
/kinect2/sd/image_ir
/kinect2/sd/image_ir/compressed
/kinect2/sd/image_ir_rect
/kinect2/sd/image_ir_rect/compressed
/kinect2/sd/points
```

As this is a little different from how the [https://wiki.ros.org/openni_launch](https://wiki.ros.org/openni_launch) package publishes the camera topics the `panda_autograsp` package is currently not working with the simulated camera. Getting the package to work with the simulated camera is not too hard, but I, unfortunately, did not yet have the time to look into this. There are multiple ways to solve this. The easiest way to get this to work is to remap the topics published from the simulated camera onto the topics the `panda_autograsp` package expects. A package which can be used to do this is the [topics_tools/relay](https://wiki.ros.org/topic_tools/relay) package. Alternatively, we can also write a simple ROS plugin for the  [common-sensors ](https://github.com/JenniferBuehler/common-sensors) package which publishes the camera images the way the `panda_autograsp` expects them.

#### Second issue

Lets now look at the second issue you are experiencing:

```
ImportError: No module named colorlog
```

This is caused by the fact that the python `colorlog` package is not installed. This package should be installed when running the `pip install` command inside your catkin workspace. However, I just noticed that this is not the cause for some python versions. I will look into this later this month. In the meantime an easy fix would be to install the package manually using the following command:
```
pip install colorlog
```
command. However, as the main `setup.py` is not working on your system, I suspect you then will be greeted by other dependency errors. The best thing to do in your case is to go into the following submodules/subfolders and also run the `pip install .` command from there:

- autolab_core
- gqcnn
- panda_autograsp
- perception
