### ISSUE TITLE
GQCNN - ROS python2 vs GQCNN python3 conflict

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/panda_autograsp#6]
When I try to run the ROS inside a conda python3 environment or the GQCNN while the ROS `setup.bash` file I experience some problems.

# Run GQCNN python package while ROS is sourced
When doing this the `/opt/ros/kinetic/lib/python2.7/` interpreter is used instead of my conda interpreter.

```
Traceback (most recent call last):
  File "examples/policy.py", line 46, in <module>
    from perception import (BinaryImage, CameraIntrinsics, ColorImage, DepthImage,
  File "/opt/conda/envs/tf-gpu/lib/python3.7/site-packages/perception/__init__.py", line 8, in <module>
    from .camera_intrinsics import CameraIntrinsics
  File "/opt/conda/envs/tf-gpu/lib/python3.7/site-packages/perception/camera_intrinsics.py", line 14, in <module>
    from .image import DepthImage, PointCloudImage
  File "/opt/conda/envs/tf-gpu/lib/python3.7/site-packages/perception/image.py", line 11, in <module>
    import cv2
ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
```

### Without source
**PATH:** `bash: /opt/conda/envs/tf-gpu/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:`
**PYTHONPATH:** ``

### With ROS source
**PATH:**`echo $PATH
/opt/ros/kinetic/bin:/opt/conda/envs/tf-gpu/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
**PYTHONPATH:**`echo $PYTHONPATH
/opt/ros/kinetic/lib/python2.7/dist-packages`
## Solutions

- Not sourcing the ROS `setup.bash` file in the `.bashrc`. Or 
- Running `unset PYTHONPATH`.
- Adding your python enviroment site-package folder to the `PYTHONPATH` enviroment variable.

- [Cannot import opencv after installing ros kinetic](https://stackoverflow.com/questions/43019951/after-install-ros-kinetic-cannot-import-opencv)
# Build ROS package inside python 3 environment
When trying to do this we get a big number of conflicts since ROS kinetic doesn't fully support python3. A number of posts are explaining the solutions to this issue.

- [Using ROS with conda](http://yuqli.com/?p=2817)
- [Conda and dealing with conflicting pythons in your system](https://dev.to/bgalvao/conda--dealing-with-conflicting-pythons-in-your-system-62n)
- [Conflicts between anaconda and ros](https://answers.ros.org/question/256886/conflict-anaconda-vs-ros-catking_pkg-not-found/)
- [How to run ROS in python3](https://answers.ros.org/question/259437/how-to-run-ros-if-your-default-python-version-is-3x-via-anaconda/)
- [How to setup ROS with python3](https://medium.com/@beta_b0t/how-to-setup-ros-with-python-3-44a69ca36674)
- [Install guide for ROS-kinetic with python 3.5](https://stackoverflow.com/questions/49758578/installation-guide-for-ros-kinetic-with-python-3-5-on-ubuntu-16-04)

## Solution
The easy straight forward solution is to remove the conda initiation and the conda environment activation from the `.bashrc.`

# Running rospackage inside conda
Since the `gqcnn/grasp_planner` node imports python modules that are installed using a `setup.py` script and ROS is python2.7 I am forced to use the 2.7 version of the GQCNN package.

**Comment by rickstaa** [comment]
Closed since problem is not an issue anymore.
